"""Harvest episodes from the enhanced environment for GSPO training.

Runs N episodes using either a heuristic policy or a saved model, collecting
the full-history prompt at each step along with ground-truth metadata.

Output format: one JSON object per line (JSONL) with fields:
  - prompt: the full-context prompt string (ready for GRPOTrainer)
  - completion: the raw response text generated by the policy
  - action: the parsed decision (APPROVE, FLAG_REVIEW, INVESTIGATE, etc.)
  - ground_truth: dict with is_fraud, provider_id, claim_amount
  - step_number: int
  - episode_seed: int

Usage:
    python scripts/harvest_episodes.py --episodes 50 --seed-start 0 --output data/train_cycle1.jsonl
    python scripts/harvest_episodes.py --episodes 50 --seed-start 100 --model checkpoints/cycle_1 --output data/train_cycle2.jsonl
"""

import argparse
import json
import re
import sys
from pathlib import Path

import torch

# Ensure project root is importable.
# In the submission repo the environment lives at environment/
# In the original training repo it lives at src/envs/healthcare_claims/
_root = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(_root))

try:
    from environment.models import ClaimAction, DecisionType
    from environment.server.environment import ClaimsFraudEnvironment, EnvironmentConfig
except ImportError:
    # Fallback to original repo path (Vast.ai training runs)
    from src.envs.healthcare_claims.models import ClaimAction, DecisionType
    from src.envs.healthcare_claims.server.environment import (
        ClaimsFraudEnvironment,
        EnvironmentConfig,
    )

# ---------------------------------------------------------------------------
# Decision extraction helper
# ---------------------------------------------------------------------------

_DECISION_RE = re.compile(
    r"DECISION:\s*(INVESTIGATE|FLAG_REVIEW|DENY|APPROVE|REQUEST_INFO)",
    re.IGNORECASE,
)
_DECISION_KEYWORDS = ["INVESTIGATE", "FLAG_REVIEW", "DENY", "APPROVE", "REQUEST_INFO"]


def extract_decision_from_text(text: str) -> str:
    """Extract the decision string from a model response."""
    match = _DECISION_RE.search(text)
    if match:
        return match.group(1).upper()
    upper = text.upper()
    for d in _DECISION_KEYWORDS:
        if d in upper:
            return d
    return "UNKNOWN"


# ---------------------------------------------------------------------------
# Heuristic policy: simple rule-based agent for Cycle 1 harvesting
# ---------------------------------------------------------------------------


def heuristic_policy(prompt: str) -> str:
    """Deterministic heuristic that inspects the prompt text.

    Strategy:
    - If "KNOWN PROVIDER" and "FRAUD" in prompt -> DENY
    - If risk assessment says HIGH -> INVESTIGATE
    - If budget remaining is 0 -> APPROVE (can't investigate)
    - Otherwise -> APPROVE
    """
    upper = prompt.upper()

    if "KNOWN PROVIDER" in upper and "FRAUD" in upper:
        decision = "DENY"
        rationale = "Provider previously investigated and found fraudulent."
        evidence = "Memory shows prior FRAUD finding for this provider."
    elif "RISK ASSESSMENT: HIGH" in upper:
        decision = "INVESTIGATE"
        rationale = "High risk score warrants investigation."
        evidence = "Risk assessment indicates HIGH risk."
    elif "BUDGET: 0/" in upper:
        decision = "APPROVE"
        rationale = "No investigation budget remaining, approving low-risk claim."
        evidence = "Budget exhausted."
    else:
        decision = "APPROVE"
        rationale = "No significant risk indicators detected."
        evidence = "Claim amount and provider profile within normal range."

    return (
        f"Decision: {decision}\n"
        f"Rationale: {rationale}\n"
        f"Evidence: {evidence}\n"
        f"Recommendation: Continue monitoring."
    )


def harvest_one_episode(
    seed: int,
    claims_per_episode: int = 100,
    policy_fn=None,
) -> list[dict]:
    """Run a single episode and return a list of prompt records."""
    if policy_fn is None:
        policy_fn = heuristic_policy

    config = EnvironmentConfig(
        claims_per_episode=claims_per_episode,
        seed=seed,
    )
    env = ClaimsFraudEnvironment(config=config)
    obs = env.reset()

    records: list[dict] = []
    step = 0

    while not obs.done:
        prompt_text = obs.prompt or obs.to_prompt()

        # Collect metadata for this step
        state = env.state
        provider_id = obs.provider_profile.get("provider_id", "???")

        # Generate action from policy
        response_text = policy_fn(prompt_text)
        action_decision = extract_decision_from_text(response_text)

        record = {
            "prompt": prompt_text,
            "completion": response_text,
            "action": action_decision,
            "ground_truth": {
                "is_fraud": env._current_is_fraud,
                "provider_id": provider_id,
                "claim_amount": obs.claim_amount,
            },
            "step_number": step,
            "episode_seed": seed,
        }
        records.append(record)

        action = ClaimAction(response_text=response_text)
        obs = env.step(action)
        step += 1

    return records


def main():
    parser = argparse.ArgumentParser(description="Harvest episode prompts for GSPO training")
    parser.add_argument("--episodes", type=int, default=50, help="Number of episodes to run")
    parser.add_argument("--seed-start", type=int, default=0, help="Starting seed")
    parser.add_argument("--claims", type=int, default=100, help="Claims per episode")
    parser.add_argument(
        "--output", type=str, default="data/train_episodes.jsonl", help="Output JSONL file path"
    )
    parser.add_argument(
        "--model",
        type=str,
        default=None,
        help="Path to saved LoRA checkpoint (uses heuristic if omitted)",
    )
    args = parser.parse_args()

    # Ensure output directory exists
    output_path = Path(args.output)
    output_path.parent.mkdir(parents=True, exist_ok=True)

    # Select policy
    if args.model:
        print(f"[INFO] Model-based harvesting from: {args.model}")
        from transformers import AutoTokenizer, AutoModelForCausalLM
        from peft import PeftModel

        # Always load the base model first, then apply LoRA adapter.
        # DO NOT use unsloth.FastLanguageModel.from_pretrained for saved checkpoints
        # as it causes an infinite hang (known bug with GSPO-trained adapters).
        base_model_id = "unsloth/Qwen2.5-1.5B-Instruct"
        harvest_tokenizer = AutoTokenizer.from_pretrained(base_model_id)

        print("[INFO] Loading base model...")
        base_model = AutoModelForCausalLM.from_pretrained(
            base_model_id,
            device_map="cuda",
            torch_dtype=torch.bfloat16,
        )

        print("[INFO] Loading LoRA adapters...")
        harvest_model = PeftModel.from_pretrained(base_model, args.model)
        harvest_model = harvest_model.merge_and_unload()
        harvest_model.eval()

        # Ensure we have the correct EOS tokens for Qwen2.5
        eos_token_ids = [
            harvest_tokenizer.convert_tokens_to_ids("<|im_end|>"),
            harvest_tokenizer.eos_token_id,
        ]

        def model_policy(prompt: str) -> str:
            """Generate a decision using the trained model."""
            # Wrap in conversational format to apply ChatML template
            messages = [{"role": "user", "content": prompt}]
            inputs = harvest_tokenizer.apply_chat_template(
                messages, tokenize=True, add_generation_prompt=True, return_tensors="pt"
            ).to("cuda")
            with torch.no_grad():
                outputs = harvest_model.generate(
                    inputs,
                    max_new_tokens=150,  # Match training budget
                    temperature=0.7,
                    do_sample=True, repetition_penalty=1.15,
                    eos_token_id=eos_token_ids,
                    pad_token_id=harvest_tokenizer.pad_token_id,
                )
            # Decode only the generated tokens (exclude input prompt tokens)
            input_length = inputs.shape[1]
            return harvest_tokenizer.decode(outputs[0][input_length:], skip_special_tokens=True)

        policy_fn = model_policy
        print("[INFO] Model loaded and ready for inference")
    else:
        print("[INFO] Using heuristic policy")
        policy_fn = heuristic_policy

    total_records = 0
    with open(output_path, "w", encoding="utf-8") as f:
        for i in range(args.episodes):
            seed = args.seed_start + i
            records = harvest_one_episode(
                seed=seed,
                claims_per_episode=args.claims,
                policy_fn=policy_fn,
            )
            for record in records:
                f.write(json.dumps(record, ensure_ascii=False) + "\n")
            total_records += len(records)

            if (i + 1) % 10 == 0:
                print(f"  Episodes: {i + 1}/{args.episodes}, Records: {total_records}")

    print(f"\n[DONE] Harvested {total_records} records from {args.episodes} episodes")
    print(f"  Output: {output_path}")


if __name__ == "__main__":
    main()
